- name: sections
  label: Page Sections
  type: block
  list: true # Often used with type: block to allow multiple sections
  blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
  blocks:
    # Each item defines a possible block structure the user can select.
    # These typically use 'component' or define 'fields' directly.
    - name: hero
      label: Add Hero Section
      component: hero # Assumes a 'hero' component is defined and that its type is `object`
    - name: text
      label: Add Text Block
      fields:
        - name: content
          label: Text Content
          type: rich-text